# Generated by Django 5.1.15 on 2026-06-21 13:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesAberto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ano', 'mes'],
                'constraints': [models.UniqueConstraint(fields=('ano', 'mes'), name='mes_aberto_unico')],
            },
        ),
        migrations.CreateModel(
            name='SaldoMensalConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_mensais', to='contas.conta')),
            ],
            options={
                'ordering': ['ano', 'mes', 'conta_id'],
                'constraints': [models.UniqueConstraint(fields=('conta', 'ano', 'mes'), name='saldo_mensal_conta_unico')],
            },
        ),
    ]
