# Generated by Django 5.1.15 on 2026-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('CARTAO', 'Cartao'), ('BANCO', 'Banco'), ('INVESTIMENTO', 'Investimento')], max_length=20)),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saldo_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('limite_negativo', models.DecimalField(blank=True, decimal_places=2, help_text='Limite negativo de referencia para alerta.', max_digits=14, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
