# Generated by Django 5.2.15 on 2026-07-23 03:06

from django.db import migrations, models


def flip_negative_to_positive(apps, schema_editor):
    Conta = apps.get_model("contas", "Conta")
    for conta in Conta.objects.filter(limite_negativo__lt=0):
        conta.limite_negativo = abs(conta.limite_negativo)
        conta.save(update_fields=["limite_negativo"])


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='limite_negativo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Informe como valor positivo (ex: 2000,00 para limite de -2000,00).', max_digits=14, null=True),
        ),
        migrations.RunPython(flip_negative_to_positive, migrations.RunPython.noop),
    ]
