# Generated by Django 5.2.15 on 2026-07-19 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('lancamentos', '0003_alter_lancamento_tipo'),
        ('parcelas', '0002_compraparcelada_fitid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitid', models.CharField(max_length=255)),
                ('chave_dedup', models.CharField(max_length=64, unique=True)),
                ('acctid', models.CharField(blank=True, max_length=255)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_importados', to='parcelas.compraparcelada')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_importados', to='contas.conta')),
                ('lancamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_importados', to='lancamentos.lancamento')),
            ],
            options={
                'verbose_name': 'Item importado',
                'verbose_name_plural': 'Itens importados',
                'ordering': ['-importado_em', '-id'],
            },
        ),
    ]
