# Generated by Django 5.1.15 on 2026-06-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('RECEBIMENTO_FIXO', 'Recebimento Fixo'), ('RECEBIMENTO_EXCEPCIONAL', 'Recebimento Excepcional'), ('GASTO_FIXO', 'Gasto Fixo'), ('GASTO_VARIAVEL', 'Gasto Variavel'), ('ASSINATURA', 'Assinatura'), ('PARCELA_CARTAO', 'Parcela de Cartao'), ('CONCILIACAO', 'Conciliacao'), ('APORTE', 'Aporte'), ('RESGATE', 'Resgate')], max_length=30)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('competencia_ano', models.PositiveIntegerField()),
                ('competencia_mes', models.PositiveSmallIntegerField()),
                ('total_parcelas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parcela_atual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gerado_automaticamente', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='contas.conta')),
                ('grupo_recorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias_recorrentes', to='lancamentos.lancamento')),
            ],
            options={
                'ordering': ['competencia_ano', 'competencia_mes', 'data_vencimento', 'id'],
            },
        ),
    ]
