# Generated by Django 5.2.15 on 2026-07-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0002_lancamento_lancamento_vinculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='tipo',
            field=models.CharField(choices=[('RECEBIMENTO_FIXO', 'Recebimento Fixo'), ('RECEBIMENTO_EXCEPCIONAL', 'Recebimento Excepcional'), ('GASTO_FIXO', 'Gasto Fixo'), ('GASTO_VARIAVEL', 'Gasto Variavel'), ('ASSINATURA', 'Assinatura'), ('PARCELA_CARTAO', 'Parcela de Cartao'), ('CONCILIACAO', 'Conciliacao'), ('APORTE', 'Aporte'), ('RESGATE', 'Resgate'), ('TRANSFERENCIA_ENVIADA', 'Transferencia Enviada'), ('TRANSFERENCIA_RECEBIDA', 'Transferencia Recebida')], max_length=30),
        ),
    ]
