# Generated by Django 5.2.15 on 2026-07-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0003_alter_lancamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='detalhes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
