# Generated by Django 5.1.15 on 2026-06-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraParcelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_parcelas', models.PositiveSmallIntegerField()),
                ('data_compra', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_parceladas', to='contas.conta')),
            ],
            options={
                'ordering': ['-data_compra', '-id'],
            },
        ),
    ]
