# Generated by Django 5.2.15 on 2026-07-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraparcelada',
            name='fitid',
            field=models.CharField(blank=True, help_text='Identificador da compra no banco de origem (importacao OFX).', max_length=255, null=True, unique=True),
        ),
    ]
