# Generated by Django 5.2.15 on 2026-07-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('parcelas', '0002_compraparcelada_fitid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraparcelada',
            name='fitid',
            field=models.CharField(blank=True, help_text='Identificador da compra no banco de origem (importacao OFX).', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='compraparcelada',
            constraint=models.UniqueConstraint(condition=models.Q(('fitid__isnull', False)), fields=('conta', 'fitid'), name='compra_fitid_unico_por_conta'),
        ),
    ]
